---
kind: pipeline
name: test-arm6

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  image: plugins/docker:19
  settings:
    dockerfile: Dockerfile
    dry_run: true
    repository: $DRONE_REPO_NAME

...
