---
kind: pipeline
name: test-arm

platform:
  os: linux
  arch: arm

steps:
- name: dryrun
  image: thegeeklab/drone-docker
  privileged: true
  settings:
    dockerfile: Dockerfile
    dry_run: true
    repo: xoxys/${DRONE_REPO_NAME}

...
