---
kind: pipeline
name: test-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: python:3.9
  commands:
  - pip install cryptography

---
kind: pipeline
name: test-arm

platform:
  os: linux
  arch: arm

steps:
- name: test
  image: python:3.9
  commands:
  - pip install cryptography

---
kind: pipeline
name: test-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: python:3.9
  commands:
  - pip install cryptography

...
